version: '3'

tasks:
  config:
    desc: Validate OpenKB Docker Compose.
    cmds:
      - '{{.COMPOSE}} config'

  build:
    cmds:
      - '{{.COMPOSE}} build openkb'

  up:
    cmds:
      - '{{.COMPOSE}} --profile tools up -d openkb'

  down:
    cmds:
      - '{{.COMPOSE}} stop openkb'

  logs:
    cmds:
      - '{{.COMPOSE}} logs -f openkb'

  compile:
    cmds:
      - '{{.COMPOSE}} run --rm {{.RUN_USER}} -e PYTHONUNBUFFERED=1 -e OLLAMA_MODEL="{{.MODEL}}" -e RAW="{{.RAW}}" -e SAMPLE="{{.SAMPLE}}" --entrypoint poe openkb -C /app compile'

  shell:
    cmds:
      - '{{.COMPOSE}} run --rm {{.RUN_USER}} --entrypoint bash openkb'

  lint:
    cmds:
      - '{{.COMPOSE}} run --rm {{.RUN_USER}} --entrypoint poe openkb -C /app lint'

  format:
    cmds:
      - '{{.COMPOSE}} run --rm {{.RUN_USER}} --entrypoint poe openkb -C /app format'

  type-check:
    cmds:
      - '{{.COMPOSE}} run --rm {{.RUN_USER}} --entrypoint poe openkb -C /app type-check'
