version: '3'

tasks:
  config:
    desc: Validate OpenKB Docker Compose.
    cmds:
      - '{{.COMPOSE}} config'

  build:
    cmds:
      - '{{.COMPOSE}} build --no-cache openkb'

  up:
    cmds:
      - '{{.COMPOSE}} --profile tools up -d openkb'

  down:
    cmds:
      - '{{.COMPOSE}} stop openkb'

  logs:
    cmds:
      - '{{.COMPOSE}} logs -f openkb'
