services:
  exporter:
    build:
      context: .
      dockerfile: Dockerfile
    image: scraper/exporter:latest
    environment:
      - TZ=Asia/Seoul
      - MONGODB_URI=mongodb://mongodb:27017/bronze
    volumes:
      - ${HOST_PROJECT_PATH:-.}/data/ebook:/app/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: "no"