version: '3'

tasks:
  config:
    cmds:
      - '{{.COMPOSE}} config'
  up:
    cmds:
      - '{{.COMPOSE}} --profile infrastructure up -d autoheal'
  down:
    cmds:
      - '{{.COMPOSE}} stop autoheal'
  logs:
    cmds:
      - '{{.COMPOSE}} logs -f autoheal'
  ps:
    cmds:
      - '{{.COMPOSE}} ps autoheal'
