version: '3'

tasks:
  config:
    desc: Validate ebook Docker Compose.
    cmds:
      - '{{.COMPOSE}} config'

  build:
    cmds:
      - '{{.COMPOSE}} build --no-cache ebook'

  up:
    cmds:
      - '{{.COMPOSE}} --profile ebook up -d ebook'

  down:
    cmds:
      - '{{.COMPOSE}} stop ebook'

  logs:
    cmds:
      - '{{.COMPOSE}} logs -f ebook'
