version: '3'

tasks:
  config:
    cmds:
      - '{{.COMPOSE}} config'
  up:
    cmds:
      - '{{.COMPOSE}} --profile tools up -d obsidian'
  down:
    cmds:
      - '{{.COMPOSE}} stop obsidian'
  logs:
    cmds:
      - '{{.COMPOSE}} logs -f obsidian'
  ps:
    cmds:
      - '{{.COMPOSE}} ps obsidian'
